version: "3.8"

services:
  chatroom:
    build: .
    depends_on:
      - mongodb
      - kratos
    networks:
      - app_network
    environment:
      - LOGIN_URL=https://127.0.0.1:4455/login
      - KRATOS_URL=http://kratos:4433

  mongodb:
    image: mongo:jammy
    # ports:
    #   - "27017:27017"
    networks:
      - app_network
  
  kratos-migrate:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - app_network

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.0.0
    environment:
      - PORT=4455
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=https://127.0.0.1:4433/
    networks:
      - app_network
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.0.0
    # ports:
    #   - '4433:4433' # public
    #   - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos/email-password
        target: /etc/config/kratos
    networks:
      - app_network

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - app_network
    
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
      - "4433:4433"
      - "4455:4455"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/:/etc/nginx/certs/
    depends_on:
      - chatroom
    networks:
      - app_network

volumes:
  postgresvol:
    external: false
  kratos-sqlite:
    external: false

networks:
  app_network:
    driver: bridge